### ISSUE TITLE
Exe or .so?

### ISSUE THREAD

**Issue by Globik** [schahriar/n-api-article#1]
Hi, thank you for your great sample in new experimental n-api.
How should be look an outputing file? Like .exe or like dynamic library?

**Comment by schahriar** [comment]
Hey @Globik, the binary is generated as a `.node` file which can be required (or imported) like any other node module. You can find the file under `/build/Release/<name>.node` after running `node-gyp configure build` which links the headers for you. (https://github.com/schahriar/n-api-article/blob/master/Getting_Started/package.json#L7)

Also if you are wondering what node-gyp does under the hood the Makefile is under the build folder.

**Comment by Globik** [comment]
Hi @schahriar , thank you for explaining. Now I understand. One can close this issue.
Only wondering right now why my linux system don't update the node.js to version 8. Is node-napi.h must be in the same directory where node.h is?
I have already made sudo apt-get update manipulation but still no reply from node.js repository about v8.6.

**Comment by Globik** [comment]
Never mind. I have uninstalled the old node.js and installed nvm.js and then node.js of new version.
The only issue is Warning: N-API is an experimental feature and could change at any time.

**Comment by schahriar** [comment]
That warning is expected for 8.x since N-API is still in experimental phase. You should see it disappear in Node 10.x once it is released.
